# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Naver-Webtoon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Naver-Webtoon
   pod 'Parchment', '~> 3.2'
end
